name: Build and push Docker container
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Read CoreOS version
      run: |
        echo "COREOS_VERSION=$(cat COREOS_VERSION)" >> $GITHUB_ENV
        echo "COREOS_VERSION=$(cat COREOS_VERSION)"

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Build container
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/sgsunder/qemu-coreos-docker:latest
          ghcr.io/sgsunder/qemu-coreos-docker:${{ env.COREOS_VERSION }}
        build-args: |
          BUILD_DATE=${{ github.event.head_commit.timestamp }}
          SOURCE_COMMIT=${{ github.sha }}
          COREOS_VERSION=${{ env.COREOS_VERSION }}
